apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payment-ledger
resources:
  - namespace.yaml
  - platform-config.yaml
  - data-platform.yaml
  - spring-services.yaml
  - frontend.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: payment-ledger-system
