apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payment-ledger
resources:
  - ../../../base/observability
  - storage.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
  - target:
      kind: Deployment
      name: zipkin
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: zipkin
  - target:
      kind: Service
      name: zipkin
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: zipkin
  - target:
      kind: Deployment
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: data
          persistentVolumeClaim:
            claimName: prometheus-data
  - target:
      kind: Deployment
      name: grafana
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
        value: grafana-secrets
      - op: replace
        path: /spec/template/spec/volumes/3
        value:
          name: data
          persistentVolumeClaim:
            claimName: grafana-data
